# Nom du projet
name = "geminiCoder"

# ID du compte Cloudflare
account_id = "b3c5e8434d2a5eba92cc671e49edf7ca"

# Configuration pour Pages
type = "javascript"
compatibility_date = "2024-12-27"

# Répertoire de sortie de la build pour Pages
pages_build_output_dir = "./dist" # Remplacez "dist" par votre répertoire de sortie réel.

# Compatibilité Node.js
node_compat = true
